# 从各自镜像的配置文件或Dockerfile启动服务
version: "3"

services:
  redis:
    image: redis:6-alpine
    restart: always
    network_mode: host
    volumes:
      - /data/redis/data:/data
  mysql:
    image: mysql:5.6
    restart: always
    network_mode: host
    volumes:
      - /vagrant/config/mysql/conf:/etc/mysql/conf.d
      - /data/mysql/data:/var/lib/mysql
      - /data/mysql/logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor333666