# Postgre image for graduation design
# Version 1.0

# 基础镜像 最新的postgres
FROM postgres:latest

# 维护者信息
MAINTAINER mambahj24@gmail.com

# 镜像操作命令
RUN apt-get update && apt-get install vim -y

# 设置环境变量
ENV POSTGRES_PASSWORD 180234sss

# 暴露端口
EXPOSE 5432


